### ISSUE TITLE
[FEATURE] Replace BWA mem with Bowtie2 in preprocessing.py 

### ISSUE THREAD

**Issue by EisenRa** [anttonalberdi/holoflow#4]
Upon testing the current preprocessing.py pipeline, I wanted to double-check that the host read removal step was working properly. The initial pipeline used BWA-mem.

My curiosity was piqued when I found that there were a substantial number of reads mapping to the human genome from a wombat faecal sample. I would not expect much, as any contaminating human DNA if present, should be at low concentrations compared to the high biomass of the faecal sample (I did the lab work very clean too):

- reads passed filtering/QC: 859,323
- microbial reads after mapping to host: 310,617
- reads in host BAM file: **548,342!!!**

I subsampled the faecal sample to 1 million paired reads (2x150bp), and used the preprocessing pipeline with the program's/pipeline's default 'loose' setting, the host reference genomes used were the human + wombat. I inspected the assembly at the read alignment level in geneious, and found that the majority of alignments were like this: 
![Untitled](https://user-images.githubusercontent.com/16024192/130381088-7d6ff44b-d725-4708-9e97-52e8d3046bc1.png)

As you can see, BWA mem is clipping ~120 bp from the alignment and only considering the 19 bp that matches exactly with the reference. This makes sense, as by default the seed length (-k) is 19 bp, the alignment score (-A) is 1, and the clipping penalty (-L) is 5. 

In this situation, the alignment score is 14 (1*19 exact matches [from -A], - 5 [from -L)

What's happening is that the clipping score is not high enough to remove these spurious alignments -- I wouldn't trust alignments shorter than 30bp, as the probability of, for example, finding any 19mer in 6 Gb reference is quite high. 

Trying above again with Bowtie2:
- reads passed filtering/QC: 859,323
- microbial reads after mapping to host: 849,241
- reads in host BAM file: **9,943**

Looks much better.

**Simulated data**
I also tested this by simulating a metagenome (30 species) that I subsampled to 1 million paired reads (2x150). I spiked in human reads at ~35%:

Using the default Bowtie2 (--sensitive & --end-to-end alignment)
- pass filtering/qc: 975,477
- microbial reads after mapping to host: 610,394
- human reads that were not mapped: 380 (or 0.1%) [_I can determine this because the read headers have the source genome from where they were derived_]
- No microbial reads were mapped to the human/wombat reference.

**Next step is to implement Bowtie2 into the preprocessing.py pipeline.**

**Comment by anttonalberdi** [comment]
Great! Could you give it a try to merge the human and wombat genomes, and see whether the new bowtie2 script properly map the reads to both genomes at the same time (randomly assigning multimapping reads)?

**Comment by EisenRa** [comment]
> 
> 
> Great! Could you give it a try to merge the human and wombat genomes, and see whether the new bowtie2 script properly map the reads to both genomes at the same time (randomly assigning multimapping reads)?

By default, Bowtie2 randomly chooses an alignment when it is met with 2 or more equally good alignments [from the manual]:

> Bowtie 2's search for alignments for a given read is "randomized." That is, when Bowtie 2 encounters a set of equally-good choices, it uses a pseudo-random number to choose. For example, if Bowtie 2 discovers a set of 3 equally-good alignments and wants to decide which to report, it picks a pseudo-random integer 0, 1 or 2 and reports the corresponding alignment.

I mapped to both the Human and Wombat reference genome (competitively), and had a look in the BAM file to check if reads were indeed being randomly placed if equally good alignments were provided:

`samtools view Sim_Meta_sensitive_sorted.bam | grep 'XS'`

[XS is specified in a bam record when multiple alignments for the same read are available]

Here are a couple of examples of such reads:
`**GCF_000001405.39_GRCh38.p13_genomic**:23:B02CBACXX:8:2315:5644:4696       163     NW_020954599.1  36363093        2      5M1I56M  =       36363098        67      **ATATGTGTATATATATATATATATATATATATATATATATATATATATATATATATATTTAG**  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  AS:i:-33        **XS**:i:-30        XN:i:0  XM:i:5  XO:i:1  XG:i:1  NM:i:6 MD:Z:2T0A1C51A2C0        YS:i:-5 YT:Z:CP`


`**GCF_000001405.39_GRCh38.p13_genomic**:23:B02CBACXX:8:2315:5644:4696       83      NW_020954599.1  36363098        2      62M      =       36363093        -67     **CTAAATATATATATATATATATATATATATATATATATATATATATATATATATACACATAT**  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  **AS**:i:-5 XS:i:0  XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:3T58      YS:i:-33 YT:Z:CP`

_NW_020954599.1 is the wombat assembly_

So it looks like the random feature is working, and splitting these low-complexity repeat sequences randomly (would expect to see identical repeat sequences between two host genomes by chance).

**Comment by anttonalberdi** [comment]
Awesome. In the meanwhile, I am updating the guide design pipeline. I will try to share this with you during the week.

**Comment by EisenRa** [comment]
Feature added and tested :-)
